#!/bin/sh

###########################################################################
# $URL: file:///var/svn/cfengine/llnl/admin/scripts/ipc_cleanup $
# $Author: tdhooge $
# $Date: 2011-06-27 11:06:30 -0700 (Mon, 27 Jun 2011) $
# $Rev: 295 $
###########################################################################

# Clean up shared memory after job

NAME=$USER #`awk -F: -v TMP=$SLURM_UID  '$3 == TMP { print $1 }' /etc/passwd`

for key in $(ipcs -mc | grep -v '^(---|key)' | awk -v USER=${NAME} '$3 == USER {print $1}'); do ipcrm -m $key; done
