# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

formats:
  - pdf
  - epub

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/dev -- docs/ .readthedocs.yaml;
        then
          exit 183;
        fi
    pre_install:
      # pip-compile was used to generate the requirements.txt file to enable
      # reproducible builds.
      #
      # If adding or updating top-level dependencies, update requirements.in and
      # then overwrite existing requirements.txt with results of `pip-compile`.
      #
      # If simply wanting to update transitive dependencies to pin a new
      # reproducible build, then overwrite existing requirements.txt with
      # results of `pip-compile`.
      #
      # https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pin-your-transitive-dependencies
      - python -m pip install pip-tools
      - pip-compile --strip-extras -o docs/new_requirements.txt docs/requirements.in --upgrade

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  # If needing to update for pinning a new reproducible build, then overwrite with
  # results of `pip-compile` command above.
  - requirements: docs/requirements.txt
