# Intel compilers
#MPICC = mpiicc
#CC = icc

MPICC = mpixlc
CC = xlc

#ZLIB = -L/usr/local/tools/zlib-1.2.6/lib -lz
#ZLIB = -L../zlib-1.2.7/install/lib -lz

# GNU compilers
#MPICC = mpicc
#CC = gcc

CFLAGS = -g -O0
LIBS = -lpthread

NUMA_HOME =
NUMA_INCS =
NUMA_LDFLAGS =
NUMA_LIBS =
#NUMA_HOME = ../numactl
#NUMA_INCS = -I$(NUMA_HOME)
#NUMA_LDFLAGS = -L$(NUMA_HOME)
#NUMA_LIBS = -lnuma

CONTAINER_HOME =
CONTAINER_INCS =
CONTAINER_LDFLAGS =
CONTAINER_LIBS =
#CONTAINER_HOME = ../container
#CONTAINER_INCS = -I$(CONTAINER_HOME)/include
#CONTAINER_LDFLAGS = -L$(CONTAINER_HOME)/lib
#CONTAINER_LIBS = -lcontainer 

UNIFYCR_LIBS = $(LIBS) $(NUMA_LIBS) $(CONTAINER_LIBS)
UNIFYCR_LDFLAGS = $(LDFLAGS) $(NUMA_LDFLAGS) $(CONTAINER_LDFLAGS)

PRE_UNIFYCR_FLAGS := $(shell echo `../install_bgq/bin/unifycr-config --pre-ld-flags`)
POST_UNIFYCR_FLAGS := $(shell echo `../install_bgq/bin/unifycr-config --post-ld-flags`)

all: test_writeread test_readwrite test_truncate test_fopen test_fprintf test_memcpy test_ramdisk

clean: 
	rm -f *.o test1 test1_container test_writeread test_readwrite test_truncate test_fopen test_fprintf test_ungetc test_scanf test_wscanf test_memcpy test_ramdisk

test1: test1.c
	$(CC) $(CFLAGS) $(INCLUDES) $(PRE_UNIFYCR_FLAGS) test1.c -o test1 $(UNIFYCR_LDFLAGS) $(UNIFYCR_LIBS) $(POST_UNIFYCR_FLAGS) $(ZLIB)

test_writeread: test_writeread.c
	$(MPICC) $(CFLAGS) $(INCLUDES) $(PRE_UNIFYCR_FLAGS) test_writeread.c -o test_writeread $(UNIFYCR_LDFLAGS) $(UNIFYCR_LIBS) $(POST_UNIFYCR_FLAGS) $(ZLIB)

test_readwrite: test_readwrite.c
	$(MPICC) $(CFLAGS) $(INCLUDES) $(PRE_UNIFYCR_FLAGS) test_readwrite.c -o test_readwrite $(UNIFYCR_LDFLAGS) $(UNIFYCR_LIBS) $(POST_UNIFYCR_FLAGS) $(ZLIB)

test_truncate: test_truncate.c
	$(MPICC) $(CFLAGS) $(INCLUDES) $(PRE_UNIFYCR_FLAGS) test_truncate.c -o test_truncate $(UNIFYCR_LDFLAGS) $(UNIFYCR_LIBS) $(POST_UNIFYCR_FLAGS) $(ZLIB)

test_fopen: test_fopen.c
	$(MPICC) $(CFLAGS) $(INCLUDES) $(PRE_UNIFYCR_FLAGS) test_fopen.c -o test_fopen $(UNIFYCR_LDFLAGS) $(UNIFYCR_LIBS) $(POST_UNIFYCR_FLAGS) $(ZLIB)

test_fprintf: test_fprintf.c
	$(MPICC) $(CFLAGS) $(INCLUDES) $(PRE_UNIFYCR_FLAGS) test_fprintf.c -o test_fprintf $(UNIFYCR_LDFLAGS) $(UNIFYCR_LIBS) $(POST_UNIFYCR_FLAGS) $(ZLIB)

test_ungetc: test_ungetc.c
	$(CC) $(CFLAGS) $(INCLUDES) $(PRE_UNIFYCR_FLAGS) test_ungetc.c -o test_ungetc $(UNIFYCR_LDFLAGS) $(UNIFYCR_LIBS) $(POST_UNIFYCR_FLAGS)  $(ZLIB)

test_scanf: test_scanf.c
	$(CC) $(CFLAGS) $(INCLUDES) $(PRE_UNIFYCR_FLAGS) test_scanf.c -o test_scanf $(UNIFYCR_LDFLAGS) $(UNIFYCR_LIBS) $(POST_UNIFYCR_FLAGS)  $(ZLIB)

test_wscanf: test_wscanf.c
	$(CC) $(CFLAGS) $(INCLUDES) $(PRE_UNIFYCR_FLAGS) test_wscanf.c -o test_wscanf $(UNIFYCR_LDFLAGS) $(UNIFYCR_LIBS) $(POST_UNIFYCR_FLAGS) $(ZLIB) 

test_memcpy: test_memcpy.c
	$(MPICC) $(CFLAGS) $(INCLUDES) test_memcpy.c -o test_memcpy $(LDFLAGS) $(LIBS) $(ZLIB)

test_ramdisk: test_ramdisk.c
	$(MPICC) $(CFLAGS) $(INCLUDES) test_ramdisk.c -o test_ramdisk $(LDFLAGS) $(LIBS) $(ZLIB)

