#!/bin/bash
set -x

mpidir=`ap mvapich2-2.3.4/install-gcc-psm2`
export PATH="${mpidir}/bin:$PATH"

if [ ! -d hdf5-1.10.2 ] ; then
  wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.2/src/hdf5-1.10.2.tar.gz
  tar -zxf hdf5-1.10.2.tar.gz
fi

pushd hdf5-1.10.2
  which mpicc

  installdir=`pwd`/install
  rm -rf $installdir

  OPT="-g -O0"
#  ./configure CFLAGS="$OPT" --prefix=${installdir} --enable-parallel --enable-build-mode=debug
  ./configure --prefix=${installdir} --enable-parallel --enable-optimization="$OPT"

  make V=1 -j
  make -j install
popd
