#!/bin/bash

. /usr/local/tools/dotkit/init.sh
use -q ic-11.1.046 

set -x

./prepare
./configure \
  --prefix=`pwd`/install \
  CC=mpicc CFLAGS="-g -O0 -fPIC -DCRUISE_GOTCHA -DENABLE_NUMA_POLICY" || exit 1
  #--disable-ld-preload \

make clean || exit 1
make || exit 1
make install || exit 1
