#
# Export variables to control UNIFYFS runtime settings.
#

#
# Source a script that is dynamically generated by 0001-setup.t.
#
source $UNIFYFS_TEST_RUN_SCRIPT

# Common settings
export UNIFYFS_LOG_VERBOSITY=${UNIFYFS_LOG_VERBOSITY:-5}
export UNIFYFS_MOUNTPOINT=${UNIFYFS_TEST_MOUNT:-"/unifyfs"}

# Server settings
export UNIFYFS_LOG_DIR=${UNIFYFS_LOG_DIR:-$UNIFYFS_TEST_STATE}
export UNIFYFS_LOG_FILE="unifyfsd.log"
export UNIFYFS_META_DB_PATH=${UNIFYFS_TEST_META}
export UNIFYFS_RUNSTATE_DIR=${UNIFYFS_TEST_STATE}
export UNIFYFS_SHAREDFS_DIR=${UNIFYFS_TEST_SHARE}

# Client settings
export UNIFYFS_LOGIO_CHUNK_SIZE=$((32 * 1024))
export UNIFYFS_LOGIO_SHMEM_SIZE=$((64 * 1048576))
export UNIFYFS_LOGIO_SPILL_SIZE=$((512 * 1048576))
export UNIFYFS_LOGIO_SPILL_DIR=${UNIFYFS_TEST_SPILL}

# In mercury 2.0.0, daemonize breaks our use of na+sm. More info
# available at https://github.com/mercury-hpc/mercury/issues/428.
# Once https://github.com/mercury-hpc/mercury/pull/430 is merged,
# and we are using a version of mercury that includes the fix,
# we can remove this setting.
export UNIFYFS_DAEMONIZE=off
