#METASTORE_HOME=/p/lscratchf/wang86/MetaStore/src
LEVELDB_HOME=/g/g0/sikich1/leveldb-1.14

METASTORE_HOME=../UnifyCR_Meta/src

all: server

server:
	mpicc -g -O0 -Wall arraylist.c unifycr_init.c unifycr_cmd_handler.c  \
		unifycr_debug.c unifycr_const.c unifycr_metadata.c \
		unifycr_request_manager.c unifycr_service_manager.c unifycr_sock.c \
		-I${METASTORE_HOME}/Mlog/ -I${METASTORE_HOME}/uthash -I${METASTORE_HOME} \
		-I${LEVELDB_HOME}/include -L${METASTORE_HOME} -DLEVELDB_SUPPORT \
		-lmdhim -lm -pthread -lstdc++ -lrt -L${LEVELDB_HOME} -lleveldb -o server

clean:
	rm server 

